services:
  - type: web
    name: rubiks-solver
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python visualization/server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        value: 5000
